### ISSUE TITLE
Failed to load local repos with reponame with mixed case

### ISSUE THREAD

**Issue by Yikun** [Yikun/reposcore#39]
Failed reading repo https://github.com/taosdata/tdengine
. Detail: No local git repo find: /opt/repos/taosdata/TDengine

Failed reading repo https://github.com/oneapi-src/onednn
. Detail: No local git repo find: /opt/repos/oneapi-src/oneDNN

Failed reading repo https://github.com/docgroup/ace_tao
. Detail: No local git repo find: /opt/repos/DOCGroup/ACE_TAO

Failed reading repo https://github.com/clusterlabs/pacemaker
. Detail: No local git repo find: /opt/repos/ClusterLabs/pacemaker

**Comment by wangxiyuan** [comment]
这个应该是大小写问题，我在新patch统一修复
